/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        page: 'var(--bg-page)',
        surface: 'var(--surface)',
        'surface-muted': 'var(--surface-muted)',
        'surface-soft': 'var(--bg-surface-soft)',
        'surface-elevated': 'var(--surface-elevated)',
        'bg-elevated': 'var(--bg-elevated)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted': 'var(--text-muted)',
        'text-inverse': 'var(--text-inverse)',
        border: 'var(--border)',
        'border-default': 'var(--border-default)',
        'border-strong': 'var(--border-strong)',
        primary: {
          DEFAULT: 'var(--primary)',
          hover: 'var(--primary-hover)',
          foreground: 'var(--primary-foreground)',
          light: 'var(--primary-light)',
          soft: 'var(--primary-soft)',
          border: 'var(--primary-border)',
          text: 'var(--primary-text)',
        },
        success: {
          DEFAULT: 'var(--success)',
          foreground: 'var(--success-foreground)',
          light: 'var(--success-light)',
          soft: 'var(--success-soft)',
          border: 'var(--success-border)',
          text: 'var(--success-text)',
        },
        warning: {
          DEFAULT: 'var(--warning)',
          foreground: 'var(--warning-foreground)',
          light: 'var(--warning-light)',
          soft: 'var(--warning-soft)',
          border: 'var(--warning-border)',
          text: 'var(--warning-text)',
        },
        danger: {
          DEFAULT: 'var(--danger)',
          foreground: 'var(--danger-foreground)',
          light: 'var(--danger-light)',
          soft: 'var(--danger-soft)',
          border: 'var(--danger-border)',
          text: 'var(--danger-text)',
        },
        info: {
          DEFAULT: 'var(--info)',
          foreground: 'var(--info-foreground)',
          light: 'var(--info-light)',
          soft: 'var(--info-soft)',
          border: 'var(--info-border)',
          text: 'var(--info-text)',
        },
        slate: {
          950: '#070B12',
          900: '#0B0F17',
          850: '#111827',
          800: '#172033',
          750: '#1E293B',
          700: '#334155',
        },
        brand: {
          blue: '#3B82F6',
          'blue-bright': '#60A5FA',
          'blue-dark': '#1D4ED8',
          accent: '#2563EB',
          emerald: '#10B981',
          amber: '#F59E0B',
          rose: '#F43F5E',
          cyan: '#06B6D4',
        }
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
